# Generated by Django 4.2.7 on 2023-12-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumesEscuchados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=30)),
                ('año', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AlbumEscuchado',
        ),
    ]
