# Generated by Django 4.2.7 on 2023-12-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0002_albumesescuchados_delete_albumescuchado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumesPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=30)),
                ('año', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='AlbumPendiente',
        ),
    ]
